<h1 dir=rtl align=center style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
نویز مشکوک
</font>
</h1>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazir">
در این بخش از مسابقه، با داده‌هایی واقعی از محیط‌های صنعتی سروکار دارید. این داده‌ها توسط سنسورهای صنعتی ثبت شده‌اند که عملکرد آن‌ها گاهی دچار اختلال یا نویز می‌شود. بروز خطا در این نوع سامانه‌ها امری طبیعی است و تشخیص به‌موقع این خطا از اهمیت بالایی برخوردار است. هدف شما در این مرحله، شناسایی داده‌هایی است که عادی نیستند از میان داده‌های عادی است؛ مسئله‌ای که در دنیای واقعی کاربردهای فراوانی در پایش سلامت تجهیزات، پیش‌بینی خرابی‌ها و افزایش ایمنی صنعتی دارد.
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
در فایل اولیه‌ی این سوال، یک پوشه با نام <code>Data</code> وجود دارد که شامل ۲ فایل <code>train.csv</code> و <code>test.csv</code>.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
این داده‌ها مربوط به فرآیندهای تولید، تجهیزات صنعتی یا سیستم‌های کنترلی هستند که به‌صورت مداوم پارامترهایی مانند دما، فشار و لرزش را ثبت می‌کنند. چنین داده‌هایی معمولاً در کاربردهای پایش وضعیت تجهیزات (Condition Monitoring) و نگهداری پیش‌گویانه (Predictive Maintenance) استفاده می‌شوند.
</font>
</p>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
هرستون این مجموعه‌داده با توجه به ماهیت خود می‌تواند مقادیر عددی یا رشته‌ای داشته باشد. برای آشنایی بیشتر با مجموعه‌داده، پیشنهاد می‌شود هرستون به صورت جداگانه بررسی شود.</font>
</p>

<h4 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه داده آموزشی (train.csv)
</font>
</h4>

<div dir="rtl">
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>

فایل <code>train.csv</code> دارای `80000` سطر و `6` ستون می‌باشد که ستون‌های آن به شرح زیر می‌باشد:

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
    

| نام ستون | توضیح |
|:---: |:---: |
| `Temperature` | دمای عملیاتی دستگاه به بر حسب درجه سلسیوس.|
| `Pressure` | فشار سیستم بر حسب بار.|
| `Vibration` |میزان لرزش قطعات متحرک دستگاه. |
| `Flow Rate` |میزان عبور سیال (مایع یا گاز) از یک لوله یا کانال را نشان می‌دهد.|
| `Humidity` |میزان رطوبت اطراف دستگاه.|
| `Rotation Speed` |سرعت چرخش موتور الکتریکی دستگاه. |


</font>
</div>
</center>
</div>

<h4 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه داده آزمون (test.csv)
</font>
</h4>

<div dir="rtl">
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
فایل <code>test.csv</code> ستون‌هایی مشابه با فایل <code>train.csv</code> می‌باشد. همچنین در این فایل <code>20000</code> سطر وجود دارد.
</font>

<font face="vazirmatn" size=3>
هدف نهایی شما این است که به ازای هر نمونه آزمایش تشخیص دهید که آیا این نمونه عادی است یا خیر.
</font>
</div>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
در این قسمت کتاب‌خانه‌ها و ابزار مورد نیاز خود را <code>import</code> کنید و فایل داده‌ها را که در پوشه‌ی <code>Data</code> و که با نام‌های <code>train.csv</code> و <code>test.csv</code> ذخیره‌شده‌اند را بخوانید و وارد محیط کار خود کنید.
</font>
</p>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_df = pd.read_csv("Data/train.csv")
test_df = pd.read_csv("Data/test.csv")
train_df

       Temperature   Pressure  Vibration  Flow Rate   Humidity  Rotation Speed
0        78.863795  39.743882   0.669183  56.130863  86.357965        2.476592
1        79.068055  36.949312   0.728419  48.480154  70.646808        6.267305
2        72.816953  32.056660   0.472869  48.715980  46.457942        4.571484
3        81.831015  42.022194   0.853386  69.521244  63.139731        5.757939
4        78.827388  34.666634   0.782639  41.104432  49.719828       19.416023
...            ...        ...        ...        ...        ...             ...
79995    72.971020  28.708468   0.604689  50.588386  22.780323        3.585721
79996    75.240264  36.276271   0.759386  53.365059  70.108093        7.412374
79997    71.775916  33.932110   0.723498  43.653249  55.961365        2.650345
79998    77.891800  28.243507   0.678259  52.457937  68.670342       13.259057
79999    76.063618  30.928039   0.703696  58.577371  44.886066        2.697296

[80000 rows x 6 columns]

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
        در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی دلخواهتان، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
    در این قسمت شما می‌توانید بخشی از داده‌ی موجود را برای اعتبارسنجی در نظر بگیرید.
</font>
</p>

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Temperature     80000 non-null  float64
 1   Pressure        80000 non-null  float64
 2   Vibration       80000 non-null  float64
 3   Flow Rate       80000 non-null  float64
 4   Humidity        80000 non-null  float64
 5   Rotation Speed  80000 non-null  float64
dtypes: float64(6)
memory usage: 3.7 MB

In [4]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

train_df_scaled = scaler.fit_transform(train_df)
test_df_scaled = scaler.transform(test_df)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
آموزش مدل
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند. در این قسمت استفاده از هر نوع مدل مربوط به یادگیری ماشین کلاسیک یا یادگیری عمیق مجاز می‌باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
در این بخش، وظیفه شما توسعه مدلی است که با استفاده از داده‌های آموزش و بدون دسترسی به برچسب‌ها (labels) بتواند تشخیص دهد که هر نمونه از داده‌های آزمون، یک نمونه عادی است یا خیر.
</font>
</p>

In [ ]:
from sklearn.ensemble import IsolationForest

X = train_df_scaled.copy()

model = IsolationForest(
    n_estimators=1500,
    contamination="auto",
    random_state=42,
)

model.fit(X)

pred = model.predict(X)

In [6]:
train_df

       Temperature   Pressure  Vibration  Flow Rate   Humidity  Rotation Speed
0        78.863795  39.743882   0.669183  56.130863  86.357965        2.476592
1        79.068055  36.949312   0.728419  48.480154  70.646808        6.267305
2        72.816953  32.056660   0.472869  48.715980  46.457942        4.571484
3        81.831015  42.022194   0.853386  69.521244  63.139731        5.757939
4        78.827388  34.666634   0.782639  41.104432  49.719828       19.416023
...            ...        ...        ...        ...        ...             ...
79995    72.971020  28.708468   0.604689  50.588386  22.780323        3.585721
79996    75.240264  36.276271   0.759386  53.365059  70.108093        7.412374
79997    71.775916  33.932110   0.723498  43.653249  55.961365        2.650345
79998    77.891800  28.243507   0.678259  52.457937  68.670342       13.259057
79999    76.063618  30.928039   0.703696  58.577371  44.886066        2.697296

[80000 rows x 6 columns]

In [7]:
train_df["is_anomaly"] = (pred == -1).astype(int)

train_df[["is_anomaly"]].value_counts()

is_anomaly
0             66805
1             13195
Name: count, dtype: int64

In [8]:
pd.DataFrame(pred).value_counts()

0
 1    66805
-1    13195
Name: count, dtype: int64

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>
    برای دریافت نمره از این سوال لازم است تا دقت مدل شما از آستانه‌ی ۰.۵۵ بیشتر باشد.
    در صورتی که دقت مدل شما از ۰.۵۵ کمتر باشد نمره شما 
   <b>صفر</b>  خواهد بود.
</font>
</p>

In [9]:
# TODO:

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
    پیش‌بینی مدل خود بر روی داده‌های آزمایش (<code>test.csv</code>) را در قالب یک <code>dataframe</code> در متغیری با نام <code>submission</code>ذخیره کنید.  این <code>dataframe</code> باید دارای یک ستون با نام <code>is_anomaly</code> باشد که ردیف <code>i</code>ام آن، پیش‌بینی شما برای سطر <code>i</code>ام مجموعه‌داده‌ی آزمون باشد.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون| توضیحات                        |
|------|--------------------------------|
|is_anomaly| اگر نمونه عادی باشد 0 و غیرعادی باشد 1|
    
</font>

</div>
</center>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>
در این ستون، برای هر نمونه از داده‌های آزمون مشخص می‌کنید که آیا آن نمونه غیرعادی است یا خیر: اگر نمونه‌ای غیرعادی باشد، مقدار ۱ در آن ردیف قرار دهید و اگر عادی باشد، مقدار ۰ در آن ردیف قرار دهید.
جدول زیر نمونه‌ای از پنج سطر فایل خروجی مورد انتظار را نشان می‌دهد:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazirmatn;font-size:medium">
<font face="vazirmatn" size=3>

|is_anomaly|
|------|
|0|
|0|
|1|
|0|
|1|

</font>
</div>
</center>

In [10]:
submission = pd.DataFrame({"is_anomaly " :  (model.predict(test_df_scaled) == -1).astype(int)})
submission.value_counts()

is_anomaly
0              16697
1               3303
Name: count, dtype: int64

<h2 dir=rtl align=right style="line-height:200%;font-family:vazirmatn;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazirmatn; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [11]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'notebook.ipynb')):
    %notebook -e notebook.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['notebook.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['notebook.ipynb', 'submission.csv']