In [160]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [161]:
customer_df = pd.read_csv("customer_master.csv")
ecommerce_df = pd.read_csv("ecommerce_sales_customer_analytics_150k.csv")
order_df = pd.read_csv("order_items.csv")
product_df = pd.read_csv("product_catalog.csv")

In [162]:
customer_df.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [163]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  object
 1   customer_name              25000 non-null  object
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  object
 4   customer_segment           25000 non-null  object
 5   customer_city              25000 non-null  object
 6   customer_state             25000 non-null  object
 7   customer_country           25000 non-null  object
 8   region                     25000 non-null  object
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

In [164]:
ecommerce_df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [165]:
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

In [166]:
order_df.head()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

In [167]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  object
 1   product_id           397569 non-null  object
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), object(2)
memory usage: 36.4+ MB

In [168]:
product_df.head()

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [169]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   object
 1   product_name         1175 non-null   object
 2   product_category     1175 non-null   object
 3   product_subcategory  1175 non-null   object
 4   brand                1175 non-null   object
 5   supplier             1175 non-null   object
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), object(6)
memory usage: 82.7+ KB

In [170]:
ecommerce_df["order_status"].unique()

array(['Completed', 'Pending', 'Cancelled', 'Returned'], dtype=object)

In [171]:
df = pd.merge(ecommerce_df, customer_df, on="customer_id")
df = pd.merge(df, order_df, on="order_id")
df = pd.merge(df, product_df, on="product_id")
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name_x,customer_age_x,gender_x,customer_segment_x,...,product_cost_y,profit_y,product_name,product_category,product_subcategory,brand,supplier,unit_price_y,product_cost,product_rating
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,173.28,172.12,Garmin Total client-driven task-force Medical ...,Health & Wellness,Medical Devices,Garmin,Euro Logistics,244.40,86.64,4.8
1,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,415.05,172.92,Tommy Hilfiger Open-architected full-range foc...,Fashion,Shoes,Tommy Hilfiger,Pacific Trade,287.13,138.35,3.0
2,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1976.16,-65.84,Swarovski Re-engineered discrete monitoring Ea...,Jewelry,Earrings,Swarovski,MultiSource,754.80,494.04,3.5
3,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,55.72,43.37,NARS Enterprise-wide actuating firmware Fragra...,Beauty & Personal Care,Fragrances,NARS,Global Trade,31.36,13.93,4.0
4,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,5.91,12.53,Mars Multi-tiered homogeneous artificial intel...,Grocery,Pantry Staples,Mars,Asian Manufacturing,6.31,1.97,3.0

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 75 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   order_id                   397569 non-null  object
 1   order_date                 397569 non-null  object
 2   order_time                 397569 non-null  object
 3   order_status               397569 non-null  object
 4   sales_channel              397569 non-null  object
 5   customer_id                397569 non-null  object
 6   customer_name_x            397569 non-null  object
 7   customer_age_x             397569 non-null  int64
 8   gender_x                   397569 non-null  object
 9   customer_segment_x         397569 non-null  object
 10  customer_type              397569 non-null  object
 11  customer_city_x            397569 non-null  object
 12  customer_state_x           397569 non-null  object
 13  customer_country_x         397569 non-null  object
 14  region_x                   397569 non-null  object
 15  customer_postal_code_x     397569 non-null  int64
 16  payment_method             397569 non-null  object
 17  payment_status             397569 non-null  object
 18  currency                   397569 non-null  object
 19  shipping_method            397569 non-null  object
 20  warehouse                  397569 non-null  object
 21  delivery_days              327028 non-null  float64
 22  estimated_delivery_days    327028 non-null  float64
 23  delivery_status            397569 non-null  object
 24  return_status              27209 non-null   object
 25  return_reason              27209 non-null   object
 26  customer_rating            327028 non-null  float64
 27  review_sentiment           327028 non-null  object
 28  customer_review            327028 non-null  object
 29  marketing_channel          397569 non-null  object
 30  campaign_name              157810 non-null  object
 31  coupon_code                79484 non-null   object
 32  loyalty_points_earned      397569 non-null  int64
 33  loyalty_points_redeemed    397569 non-null  int64
 34  quantity_x                 397569 non-null  int64
 35  gross_sales_x              397569 non-null  float64
 36  discount_amount_x          397569 non-null  float64
 37  tax_amount_x               397569 non-null  float64
 38  shipping_cost_x            397569 non-null  float64
 39  net_sales_x                397569 non-null  float64
 40  product_cost_x             397569 non-null  float64
 41  profit_x                   397569 non-null  float64
 42  profit_margin_percentage   397569 non-null  float64
 43  customer_lifetime_value    397569 non-null  float64
 44  is_repeat_customer         397569 non-null  bool
 45  customer_order_count       397569 non-null  int64
 46  customer_name_y            397569 non-null  object
 47  customer_age_y             397569 non-null  int64
 48  gender_y                   397569 non-null  object
 49  customer_segment_y         397569 non-null  object
 50  customer_city_y            397569 non-null  object
 51  customer_state_y           397569 non-null  object
 52  customer_country_y         397569 non-null  object
 53  region_y                   397569 non-null  object
 54  customer_postal_code_y     397569 non-null  int64
 55  customer_acquisition_cost  397569 non-null  float64
 56  product_id                 397569 non-null  object
 57  quantity_y                 397569 non-null  int64
 58  unit_price_x               397569 non-null  float64
 59  discount_percentage        397569 non-null  float64
 60  discount_amount_y          397569 non-null  float64
 61  gross_sales_y              397569 non-null  float64
 62  tax_amount_y               397569 non-null  float64
 63  shipping_cost_y            397569 non-null  float64
 64  net_sales_y                397569 non-null  float64
 65  product_cost_y             397569 non-null  float64
 66  profit_y                   397569 non-null  float64
 67  product_name               397569 non-null  object
 68  product_category           397569 non-null  object
 69  product_subcategory        397569 non-null  object
 70  brand                      397569 non-null  object
 71  supplier                   397569 non-null  object
 72  unit_price_y               397569 non-null  float64
 73  product_cost               397569 non-null  float64
 74  product_rating             397569 non-null  float64
dtypes: bool(1), float64(25), int64(9), object(40)
memory usage: 224.8+ MB

In [173]:
df.drop(columns=["order_id" , "customer_id" , "product_id" , "order_date" , "order_time"] , inplace=True)

In [174]:
df["order_status"] = (df["order_status"] == "Returned").astype(int)

In [175]:
df["sales_channel"].unique()

array(['Mobile App', 'Website', 'Social Media', 'Marketplace'],
      dtype=object)

In [176]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler

oneHot_column = ["sales_channel"]
label_column = []

ct = ColumnTransformer(
    [
        ("one-hot-encoder", OneHotEncoder(sparse_output=False), oneHot_column),
        ("label-encoder", LabelEncoder(), label_column),
    ],
    remainder="passthrough"
)

df_transformed = ct.fit_transform(df)

feature_names = ct.get_feature_names_out()

df = pd.DataFrame(
    df_transformed,
    columns=feature_names,
    index=df.index
)

In [177]:
df

,one-hot-encoder__sales_channel_Marketplace,one-hot-encoder__sales_channel_Mobile App,one-hot-encoder__sales_channel_Social Media,one-hot-encoder__sales_channel_Website,remainder__order_status,remainder__customer_name_x,remainder__customer_age_x,remainder__gender_x,remainder__customer_segment_x,remainder__customer_type,...,remainder__product_cost_y,remainder__profit_y,remainder__product_name,remainder__product_category,remainder__product_subcategory,remainder__brand,remainder__supplier,remainder__unit_price_y,remainder__product_cost,remainder__product_rating
0,0.0,1.0,0.0,0.0,0,Jasmine Ryan,55,Male,Consumer,Loyal,...,173.28,172.12,Garmin Total client-driven task-force Medical ...,Health & Wellness,Medical Devices,Garmin,Euro Logistics,244.4,86.64,4.8
1,0.0,1.0,0.0,0.0,0,Jasmine Ryan,55,Male,Consumer,Loyal,...,415.05,172.92,Tommy Hilfiger Open-architected full-range foc...,Fashion,Shoes,Tommy Hilfiger,Pacific Trade,287.13,138.35,3.0
2,0.0,0.0,0.0,1.0,0,Scott Chase,26,Male,Premium,Loyal,...,1976.16,-65.84,Swarovski Re-engineered discrete monitoring Ea...,Jewelry,Earrings,Swarovski,MultiSource,754.8,494.04,3.5
3,0.0,0.0,0.0,1.0,0,Scott Chase,26,Male,Premium,Loyal,...,55.72,43.37,NARS Enterprise-wide actuating firmware Fragra...,Beauty & Personal Care,Fragrances,NARS,Global Trade,31.36,13.93,4.0
4,0.0,1.0,0.0,0.0,0,Marc Wheeler,69,Female,Premium,Loyal,...,5.91,12.53,Mars Multi-tiered homogeneous artificial intel...,Grocery,Pantry Staples,Mars,Asian Manufacturing,6.31,1.97,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397564,0.0,0.0,1.0,0.0,0,Charles Hanson,46,Female,Consumer,Loyal,...,142.54,105.86,Pure Vitamin Universal interactive concept Fir...,Health & Wellness,First Aid,Pure Vitamin,Euro Logistics,137.53,71.27,3.2
397565,0.0,0.0,1.0,0.0,0,Charles Hanson,46,Female,Consumer,Loyal,...,280.8,293.9,Kong Stand-alone high-level hierarchy Pet Food,Pet Supplies,Pet Food,Kong,Direct Import,118.96,56.16,2.8
397566,0.0,0.0,1.0,0.0,0,Charles Hanson,46,Female,Consumer,Loyal,...,64.47,80.15,Penguin Extended leadingedge intranet Comics,Books & Media,Comics,Penguin,MultiSource,52.5,21.49,3.1
397567,0.0,1.0,0.0,0.0,0,John Miller,28,Male,Consumer,Loyal,...,564.86,544.0,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
397568,0.0,1.0,0.0,0.0,0,John Miller,28,Male,Consumer,Loyal,...,319.6,134.67,Williams-Sonoma Organized leadingedge framewor...,Home & Kitchen,Decor,Williams-Sonoma,Amazon Supply,151.53,63.92,3.2